### ISSUE TITLE
i hope ycnbc has new function about stock data

### ISSUE THREAD

**Issue by suhaocong** [asepscareer/ycnbc#1]
*** READ BEFORE POSTING ***

Before posting an issue - please upgrade to the latest version and confirm the issue/bug is still there.

Upgrade using:
`$ pip install ycnbc --upgrade --no-cache-dir`

Bug still there? Delete this content and submit your bug report here...

**Comment by codestorm-official** [comment]
You can use this for the time being:

```python
quote_summary = markets.quote_summary('AAPL')
```

thanks.
